In [12]:
import pandas as pd

Se importa Dataset de entrenamiento y el de simulación

In [13]:
drive.mount('/content/drive')

ruta_train = '/content/drive/My Drive/Training_And_Testing_Dataset/smoking_prediction.csv'
ruta_test = '/content/drive/My Drive/Training_And_Testing_Dataset/smoking_prediction_entrega.csv'
df_train = pd.read_csv(ruta_train)
df_test = pd.read_csv(ruta_test)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Se revista estado de dataset de entrenamiento, identificando la columna "Smoking" que contiene las etiquetas binarias que se utilizaran para entrenar los modelos.
Tambien se verifica la cantidad de datos por variables y su tipo, sin nulos.

In [14]:
print("--- DATASET DE ENTRENAMIENTO ---")
print(f"Dimensiones: {df_train.shape[0]} filas y {df_train.shape[1]} columnas.")
print("\nInformación general de las columnas:")
df_train.info()

--- DATASET DE ENTRENAMIENTO ---
Dimensiones: 50000 filas y 27 columnas.

Información general de las columnas:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   50000 non-null  int64
 1   gender               50000 non-null  object
 2   age                  50000 non-null  int64
 3   height(cm)           50000 non-null  int64
 4   weight(kg)           50000 non-null  int64
 5   waist(cm)            50000 non-null  float64
 6   eyesight(left)       50000 non-null  float64
 7   eyesight(right)      50000 non-null  float64
 8   hearing(left)        50000 non-null  float64
 9   hearing(right)       50000 non-null  float64
 10  systolic             50000 non-null  float64
 11  relaxation           50000 non-null  float64
 12  fasting blood sugar  50000 non-null  float64
 13  Cholesterol          50000 non-null  float64
 14  triglyceride         50000 non-null  float64
 15  HDL                  50000 non-null  float64
 16  LDL                  50000 non-null  float64
 17  hemoglobin           50000 non-null  float64
 18  Urine protein        50000 non-null  float64
 19  serum creatinine     50000 non-null  float64
 20  AST                  50000 non-null  float64
 21  ALT                  50000 non-null  float64
 22  Gtp                  50000 non-null  float64
 23  oral                 50000 non-null  object
 24  dental caries        50000 non-null  int64
 25  tartar               50000 non-null  object
 26  smoking              50000 non-null  int64
dtypes: float64(18), int64(6), object(3)
memory usage: 10.3+ MB

Se verifica que el dataset de simulación es carente de la columna de sesgo binario, de menor volumen de datos, conteniendo las mismas variables principales que el dataset de entrenamiento, sin nulos.

In [15]:
print("--- DATASET DE SIMULACIÓN ---")
print(f"Dimensiones: {df_test.shape[0]} filas y {df_test.shape[1]} columnas.")
print("\nInformación general de las columnas:")
df_test.info()

--- DATASET DE SIMULACIÓN ---
Dimensiones: 5692 filas y 26 columnas.

Información general de las columnas:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5692 entries, 0 to 5691
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   5692 non-null   int64
 1   gender               5692 non-null   object
 2   age                  5692 non-null   int64
 3   height(cm)           5692 non-null   int64
 4   weight(kg)           5692 non-null   int64
 5   waist(cm)            5692 non-null   float64
 6   eyesight(left)       5692 non-null   float64
 7   eyesight(right)      5692 non-null   float64
 8   hearing(left)        5692 non-null   float64
 9   hearing(right)       5692 non-null   float64
 10  systolic             5692 non-null   float64
 11  relaxation           5692 non-null   float64
 12  fasting blood sugar  5692 non-null   float64
 13  Cholesterol          5692 non-null   float64
 14  triglyceride         5692 non-null   float64
 15  HDL                  5692 non-null   float64
 16  LDL                  5692 non-null   float64
 17  hemoglobin           5692 non-null   float64
 18  Urine protein        5692 non-null   float64
 19  serum creatinine     5692 non-null   float64
 20  AST                  5692 non-null   float64
 21  ALT                  5692 non-null   float64
 22  Gtp                  5692 non-null   float64
 23  oral                 5692 non-null   object
 24  dental caries        5692 non-null   int64
 25  tartar               5692 non-null   object
dtypes: float64(18), int64(5), object(3)
memory usage: 1.1+ MB

Se observan las columnas y las primeras filas de los datasets

In [16]:
display(df_train.head())

,ID,gender,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),...,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,oral,dental caries,tartar,smoking
0,0,F,40,155,60,3.38,0.04,0.04,0.04,0.04,...,0.51,0.04,0.00,0.75,0.79,1.13,Y,0,Y,0
1,1,F,40,160,60,3.38,0.01,0.00,0.04,0.04,...,0.50,0.04,0.00,0.92,0.79,0.75,Y,0,Y,0
2,2,M,55,170,60,3.33,0.01,0.01,0.04,0.04,...,0.63,0.04,0.04,0.88,0.67,0.92,Y,0,N,1
3,3,M,40,165,70,3.67,0.05,0.05,0.04,0.04,...,0.59,0.04,0.04,0.79,1.08,0.75,Y,0,Y,0
4,4,F,40,155,60,3.58,0.04,0.04,0.04,0.04,...,0.50,0.04,0.00,0.67,0.58,0.92,Y,0,N,0

In [17]:
display(df_test.head())

,ID,gender,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),...,LDL,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,oral,dental caries,tartar
0,27358,M,25,160,65,3.42,0.05,0.00,0.04,0.04,...,3.04,0.63,0.04,0.01,0.75,0.71,0.71,Y,0,Y
1,27364,M,30,180,80,3.46,0.04,0.01,0.04,0.04,...,4.21,0.59,0.04,0.04,0.79,1.13,1.33,Y,0,N
2,27368,M,55,165,60,3.42,0.00,0.01,0.04,0.04,...,2.04,0.63,0.04,0.01,1.08,1.29,2.00,Y,1,Y
3,27378,M,20,175,75,3.63,0.05,0.05,0.04,0.04,...,3.71,0.63,0.04,0.04,0.83,0.58,0.46,Y,0,N
4,27381,M,25,165,80,3.79,0.04,0.04,0.04,0.04,...,6.63,0.67,0.04,0.04,1.25,1.63,1.96,Y,1,Y